var annotated_dup =
[
    [ "ArrayAccessExpr", "classArrayAccessExpr.html", "classArrayAccessExpr" ],
    [ "ASTNode", "classASTNode.html", "classASTNode" ],
    [ "BinaryExpr", "classBinaryExpr.html", "classBinaryExpr" ],
    [ "BlockStmt", "classBlockStmt.html", "classBlockStmt" ],
    [ "BreakStmt", "classBreakStmt.html", "classBreakStmt" ],
    [ "CallExpr", "classCallExpr.html", "classCallExpr" ],
    [ "CodeGenerator", "classCodeGenerator.html", null ],
    [ "CommaExpr", "classCommaExpr.html", "classCommaExpr" ],
    [ "Command", "structCommand.html", null ],
    [ "ContinueStmt", "classContinueStmt.html", "classContinueStmt" ],
    [ "DoWhileStmt", "classDoWhileStmt.html", "classDoWhileStmt" ],
    [ "Expression", "classExpression.html", "classExpression" ],
    [ "ExprStmt", "classExprStmt.html", "classExprStmt" ],
    [ "ForStmt", "classForStmt.html", "classForStmt" ],
    [ "FunctionDecl", "classFunctionDecl.html", "classFunctionDecl" ],
    [ "IdentifierExpr", "classIdentifierExpr.html", "classIdentifierExpr" ],
    [ "IfStmt", "classIfStmt.html", "classIfStmt" ],
    [ "Lexer", "classLexer.html", null ],
    [ "LiteralExpr", "classLiteralExpr.html", "classLiteralExpr" ],
    [ "Parameter", "structParameter.html", "structParameter" ],
    [ "Program", "classProgram.html", "classProgram" ],
    [ "ReturnStmt", "classReturnStmt.html", "classReturnStmt" ],
    [ "SemanticAnalyzer", "classSemanticAnalyzer.html", "classSemanticAnalyzer" ],
    [ "Token", "structToken.html", null ],
    [ "Type", "structType.html", "structType" ],
    [ "UnaryExpr", "classUnaryExpr.html", "classUnaryExpr" ],
    [ "VarDecl", "classVarDecl.html", "classVarDecl" ],
    [ "WhileStmt", "classWhileStmt.html", "classWhileStmt" ]
];